/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using sample.Client;
using sample.Api;
// uncomment below to import models
//using sample.Model;

namespace sample.Test.Api
{
    /// <summary>
    ///  Class for testing ItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ItemsApiTests : IDisposable
    {
        private ItemsApi instance;

        public ItemsApiTests()
        {
            instance = new ItemsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ItemsApi
            //Assert.IsType<ItemsApi>(instance);
        }

        /// <summary>
        /// Test GetItems
        /// </summary>
        [Fact]
        public void GetItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetItems();
            //Assert.IsType<Items>(response);
        }
    }
}
