/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using sample.Client;
using sample.Api;
// uncomment below to import models
//using sample.Model;

namespace sample.Test.Api
{
    /// <summary>
    ///  Class for testing UserApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class UserApiTests : IDisposable
    {
        private UserApi instance;

        public UserApiTests()
        {
            instance = new UserApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' UserApi
            //Assert.IsType<UserApi>(instance);
        }

        /// <summary>
        /// Test CreateUser
        /// </summary>
        [Fact]
        public void CreateUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //User user = null;
            //var response = instance.CreateUser(user);
            //Assert.IsType<User>(response);
        }

        /// <summary>
        /// Test DeleteUserById
        /// </summary>
        [Fact]
        public void DeleteUserByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.DeleteUserById(id);
            //Assert.IsType<User>(response);
        }

        /// <summary>
        /// Test GetUserById
        /// </summary>
        [Fact]
        public void GetUserByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.GetUserById(id);
            //Assert.IsType<User>(response);
        }

        /// <summary>
        /// Test GetUsers
        /// </summary>
        [Fact]
        public void GetUsersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetUsers();
            //Assert.IsType<List<User>>(response);
        }

        /// <summary>
        /// Test UpdateUserById
        /// </summary>
        [Fact]
        public void UpdateUserByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //User user = null;
            //var response = instance.UpdateUserById(id, user);
            //Assert.IsType<User>(response);
        }
    }
}
