/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = sample.Client.FileParameter;
using OpenAPIDateConverter = sample.Client.OpenAPIDateConverter;

namespace sample.Model
{
    /// <summary>
    /// 性別
    /// </summary>
    /// <value>性別</value>
    public enum Gender
    {
        /// <summary>
        /// Enum male for value: 0
        /// </summary>
        male = 0,

        /// <summary>
        /// Enum female for value: 1
        /// </summary>
        female = 1,

        /// <summary>
        /// Enum others for value: 2
        /// </summary>
        others = 2
    }

}
