/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = sample.Client.FileParameter;
using OpenAPIDateConverter = sample.Client.OpenAPIDateConverter;

namespace sample.Model
{
    /// <summary>
    /// 製造元情報
    /// </summary>
    [DataContract(Name = "Item_manufacturer")]
    public partial class ItemManufacturer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemManufacturer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ItemManufacturer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemManufacturer" /> class.
        /// </summary>
        /// <param name="name">メーカー名 (required).</param>
        /// <param name="country">国 (required).</param>
        public ItemManufacturer(string name = default, string country = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for ItemManufacturer and cannot be null");
            }
            this.Name = name;
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new ArgumentNullException("country is a required property for ItemManufacturer and cannot be null");
            }
            this.Country = country;
        }

        /// <summary>
        /// メーカー名
        /// </summary>
        /// <value>メーカー名</value>
        /*
        <example>新進気鋭のメーカーさん</example>
        */
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// 国
        /// </summary>
        /// <value>国</value>
        /*
        <example>日本</example>
        */
        [DataMember(Name = "country", IsRequired = true, EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ItemManufacturer {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
