/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = sample.Client.FileParameter;
using OpenAPIDateConverter = sample.Client.OpenAPIDateConverter;

namespace sample.Model
{
    /// <summary>
    /// 商品リスト
    /// </summary>
    [DataContract(Name = "Items")]
    public partial class Items : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Items" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Items() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Items" /> class.
        /// </summary>
        /// <param name="totalCount">総商品数 (required).</param>
        /// <param name="varItems">商品一覧 (required).</param>
        public Items(int totalCount = default, List<Item> varItems = default)
        {
            this.TotalCount = totalCount;
            // to ensure "varItems" is required (not null)
            if (varItems == null)
            {
                throw new ArgumentNullException("varItems is a required property for Items and cannot be null");
            }
            this.VarItems = varItems;
        }

        /// <summary>
        /// 総商品数
        /// </summary>
        /// <value>総商品数</value>
        /*
        <example>2</example>
        */
        [DataMember(Name = "totalCount", IsRequired = true, EmitDefaultValue = true)]
        public int TotalCount { get; set; }

        /// <summary>
        /// 商品一覧
        /// </summary>
        /// <value>商品一覧</value>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<Item> VarItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Items {\n");
            sb.Append("  TotalCount: ").Append(TotalCount).Append("\n");
            sb.Append("  VarItems: ").Append(VarItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
