/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sample.Model;
using sample.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sample.Test.Model
{
    /// <summary>
    ///  Class for testing ItemManufacturer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemManufacturerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemManufacturer
        //private ItemManufacturer instance;

        public ItemManufacturerTests()
        {
            // TODO uncomment below to create an instance of ItemManufacturer
            //instance = new ItemManufacturer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemManufacturer
        /// </summary>
        [Fact]
        public void ItemManufacturerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemManufacturer
            //Assert.IsType<ItemManufacturer>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
    }
}
