/*
 * サンプル用API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using sample.Model;
using sample.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace sample.Test.Model
{
    /// <summary>
    ///  Class for testing Items
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Items
        //private Items instance;

        public ItemsTests()
        {
            // TODO uncomment below to create an instance of Items
            //instance = new Items();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Items
        /// </summary>
        [Fact]
        public void ItemsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Items
            //Assert.IsType<Items>(instance);
        }

        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

        /// <summary>
        /// Test the property 'VarItems'
        /// </summary>
        [Fact]
        public void VarItemsTest()
        {
            // TODO unit test for the property 'VarItems'
        }
    }
}
